init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd CreatePackages
  - cmd: build.cmd UnitTests
  - cmd: build.cmd ConventionTests
test: off
artifacts:
- path: '**\*.nupkg'
deploy:
  provider: NuGet
  artifact: /.*\.nupkg/
